#!/bin/bash
export script="$0"
if ! test -e "$HOME"/.arcchat.conf; then
echo "var=1" > "$HOME"/.arcchat.conf
echo "ip=173.75.48.65" >> "$HOME"/.arcchat.conf
echo "source \"\$script\"" >> "$HOME"/.arcchat.conf
fi
if [ "$var" = "" ]; then
chmod +x "$HOME"/.arcchat.conf
source "$HOME"/.arcchat.conf
exit
elif [ "$1" = -a ]; then
grep -v ip=$ip "$HOME"/.arcchat.conf > temp; mv temp "$HOME"/.arcchat.conf
printf '%s\n' H 2i "ip=$2" . w | ed -s "$HOME"/.arcchat.conf
chmod +x "$HOME"/.arcchat.conf
exit
elif [ "$1" = --address ]; then
grep -v ip=$ip "$HOME"/.arcchat.conf > temp; mv temp "$HOME"/.arcchat.conf
printf '%s\n' H 2i "ip=$2" . w | ed -s "$HOME"/.arcchat.conf
chmod +x "$HOME"/.arcchat.conf
exit
elif ! [ "$first" = "" ]; then
echo "Answer yes to all prompts about security fingerprints"
ssh messenger@$ip
exit
elif [ "$LC_name" = "" ]; then
 echo "Would you like a preset username [y/n]"
 read answer
 case $answer in
   y)
 echo 'What would you like your preset username to be (Real name) (No Spaces\)(Prefrebly no caps)'
 read name
 printf '%s\n' H 2i "export LC_name=$name" . w | ed -s "$HOME"/.arcchat.conf
  ;;

  n)
 echo "Ok"
  ;; 

  *)
 echo "Ok, aborting"
  ;;

 esac
fi
if [ "$firstrun" = "" ]; then
chmod +x "$HOME"/.arcchat.conf
echo "Would you like to enable passwordless/special login [y/n]"
read answer
case $answer in
   y)
  echo This will prompt you to make a password P.S. no password is TOTALY OK \(You can use biometric id as a password\)
  ssh-keygen
  echo Now type in the password to the server \(Answer yes to all prompts about security fingerprints\)
  ssh-copy-id messenger@"$ip"
  ;;

   n)
  echo Ok
  echo Would you like to generate a script to enable passwordless/special login later [y/n]
  read answer
  if [ "$answer" = y ]; then
   echo \#\!/bin/bash > ~/Desktop/SetupPasswordLessLogin
   echo -e "echo This will prompt you to make a password P.S. no password is TOTALY OK\nssh-keygen\necho Now type in the password to the server\nssh-copy-id messenger@$ip\necho BTW would you like to remove this script[y/N]\nread choice\nif [ \"\$choice\" = y ]; then\nrm \"\$0\"\nexit\nelif [ \"\$choice\" = Y ]; then\nrm \"\$0\"\nexit\nfi" >> ~/Desktop/SetupPasswordLessLogin 
   chmod +x ~/Desktop/Setuppasswordlesslogin
   echo NOTE: This Script will be valid for about 3 months
  else
  echo Ok
  fi
   ;; 

   *)
  echo "Ok, aborting"
  ;;

 esac
printf '%s\n' H 2i "firstrun=1" . w | ed -s "$HOME"/.arcchat.conf
first=1 "$HOME"/.arcchat.conf
exit
fi
ssh messenger@$ip
